[id='Security-Strategy-Keycloak-{chapter}']
= Security Strategy for {WFM-RC-NameShort} Keycloak

== Session Management
Keycloak uses the Express middleware `Express Sessions` module for the {WFM-RC-NameShort} cloud server.
One of the key functions of Keycloak is you can administer sessions on the
link:https://keycloak.gitbooks.io/documentation/server_admin/topics/sessions/administering.html[Keycloak server]

== Access Control
Keycloak has role based access control. This can be configured on the Keycloak server see
link:https://keycloak.gitbooks.io/documentation/server_admin/topics/roles.html[roles administration] for more information.

== Password Storage
With the default configuration of Keycloak passwords are stored on the Keycloak server. Access to user passwords is restricted.
Keycloak has a number of Password Policy available which are documented on the link:https://keycloak.gitbooks.io/documentation/server_admin/topics/authentication/password-policies.html[Keycloak password policy documentation].
Keycloak can be configured to use link:https://keycloak.gitbooks.io/documentation/server_admin/topics/identity-broker.html[external providers]
like `OAuth/SAML/Open ID Connect` or link:https://keycloak.gitbooks.io/documentation/server_admin/topics/user-federation.html[user federation]
with `ldap/Kerberous`. So it is not always the case that passwords are store on the Keycloak server.

== Authentication
Keycloak has a wide variety of Authentication mechanisms available to it see the
link:https://keycloak.gitbooks.io/documentation/server_admin/topics/authentication.html[Keycloak Documentation].

== Authorisation
Authorisation is documented fully in the link:https://keycloak.gitbooks.io/documentation/authorization_services/index.html[Keycloak Documentaion]