[id='{context}-con-introducing-securityfeatures']
= Introducing {PROJECT_NAME} Security Features

*{PROJECT_NAME}* Security is built around a *Security Interface* which abstracts itself from all *{PROJECT_NAME}* security libraries.
*{PROJECT_NAME}* allows you to integrate a custom security solution.
*{PROJECT_NAME}* also provides two out-of-the-box security implementations called link:http://www.keycloak.org/[Keycloak] and link:http://passportjs.org/[Passport.js].

*Keycloak* and *Passport.js* both provide server side authentication and authorization.
*Keycloak* and *Passport.js* implementations are interchangeable since they implement the *{PROJECT_NAME}* *Security Interface*, and thus can operate with all modules and also any of the reference applications.

== Authorization using the Security Interface
If you build a custom security implementation, the endpoints are secured in the same way as the *Keycloak* and *Passport.js* implementations.

If you choose to build a custom security implementation, you will need to:

 . Import the link:../../../api/{WFM-RC-Api-Version}{WFM-RC-Api-Endpoint-Security}[EndpointSecurity] interface from the *Passport.js* implementation
 . Implement the interface in the custom security implementation
 . Use the _protect_ method to guard routes (the security permissions being role based)

NOTE: All link:https://expressjs.com/[express] routes outside of {PROJECT_NAME} modules must implement the link:../../../api/{WFM-RC-Api-Version}{WFM-RC-Api-Endpoint-Security}[EndpointSecurity] Security Interface.

== Introducing Passport.js

*Passport.js* is a lightweight authentication middleware solution for Node.js and can be bundled into an existing Node.js server.
*Passport.js* offers a comprehensive set of link:http://passportjs.org/docs/configure[strategies] that support authentication using a username and password, existing social media and other 3rd party accounts, and more.

For more information, see link:http://passportjs.org/[passportjs.org].

The *link:{WFM-RC-CoreTreeURL}{WFM-RC-Branch}/cloud/passportauth[PassportAuth Module]* is *{PROJECT_NAME}'s* implementation of *Passport.js* and is the default authentication and authorization module for *{PROJECT_NAME}*.

== Introducing {Keycloak}

*Keycloak* is a complete identity management solution. It extends standard authorization and authentication functionality, and comes with all the overheads involved in running a separate server.
Red Hat recommends using *Keycloak* in production to avail of the many features available for enterprise security including:

* Single-Sign On
* User Federation
* Client Cert Authentication
* 2FA with OTP
* User Session Management
* Auditing
* Brute Force Detection

NOTE: *Keycloak* is _not_ available by default when running the default {PROJECT_NAME} solution.

== Choosing Passport.js or Keycloak
*Passport.js*:

* If you want a standalone Node.js based authentication solution that is ready out-of-the-box, choose *Passport.js*.

*Keycloak*:

* If you want a full identity management solution that can be tied into existing SAML/LDAP/SSO solutions, choose *Keycloak*.
