
= Overview

{PROJECT_NAME} allows you to move from paper based forms and processes into complete mobile solution.
{PROJECT_NAME} connects a business back-office portal application with its fleet of mobilized employees via a mobile application.
Both mobile and portal applications are fully customizable.

== 1.1.0 Release

=== Starting the server application

In previous releases of raincatcher the 'npm run start' command ran the project using the link:https://github.com/TypeStrong/ts-node[TypeScript Node] source code. With this release, that command now runs compiled JavaScript. 
If you want to run the project using TypeScript source code:

`npm run start:ts`.

=== File storage and Camera integration

{PROJECT_NAME} steps can now capture and store photos using the underlying file storage server.
For more information, see the link:#{context}-con-file-storage[File storage documentation].

== 1.0.0 Release
{PROJECT_NAME} 1.0.0 is a new product that was previously in tech preview. The Features are listed below.

=== Workflows
The ability to create customizable processes (called Workflows). Workflows are made up of Steps which can be the Packaged Steps
or can be custom Steps developed for a particular use case.

=== Workorders
The ability to process instances called Workorders. Workorders are a instance of an individual workflow.
Workorder can be assigned via the Portal Application to individual employees as a job for completion.

=== Step Generator
Generates a Step via a CLI, the step can be customized to meet a use case.

=== Packaged Step
Providing predefined signature Step that can be used for any business needs.
