
= Overview

{PROJECT_NAME} allows you to move from paper based forms and processes into complete mobile solution.
{PROJECT_NAME} connects a business back-office portal application with its fleet of mobilized employees via a mobile application.
Both mobile and portal applications are fully customizable.

== 1.1.0 Release

=== Starting the applications
The `npm run start` command now runs the compiled JavaScript code as opposed to utilizing link:https://github.com/TypeStrong/ts-node[TypeScript Node] to run everything from the TypeScript sources.

The previous behavior is still achievable via `npm run start:ts`.

== 1.0.0 Release
{PROJECT_NAME} 1.0.0 is a new product that was previously in tech preview. The Features are listed below.

=== Workflows
The ability to create customizable processes (called Workflows). Workflows are made up of Steps which can be the Packaged Steps
or can be custom Steps developed for a particular use case.

=== Workorders
The ability to process instances called Workorders. Workorders are a instance of an individual workflow.
Workorder can be assigned via the Portal Application to individual employees as a job for completion.

=== Step Generator
Generates a Step via a CLI, the step can be customized to meet a use case.

=== Packaged Step
Providing predefined signature Step that can be used for any business needs.
