[id='{context}-con-datasync']
= Introducing the {PROJECT_NAME} Datasync Module

The *{PROJECT_NAME} Datasync* Module is an implementation of the *{ProductShortName}* Sync Framework.
*Datasync* is made up of two modules, the xref:{context}-datasync-cloud-module[Cloud module] and the xref:{context}-datasync-client-module[Client module].
The primary function of *Datasync* is to synchronize data, for example, a _workorder_, between the Client Application (mobile) and the backend server.

*Datasync* key features:

- Allows mobile applications to use and update data while being offline
- Provides a mechanism to manage bi-directional data synchronization from multiple clients into back-end data stores via the server.
- Allows data updates (that is, deltas) to be distributed from the server to connected clients
- Provides facilities for managing data collisions from multiple updates in the cloud

For advanced usage of the *Datasync* module, see the link:https://access.redhat.com/documentation/en-us/red_hat_mobile_application_platform/4.4/html/server-side_developer_guide/server-side-developer-guide-using-rhmap-data-sync-framework[Sync Documentation]

[id='{context}-datasync-cloud-module']
== Datasync Cloud
The *Datasync Cloud* is a wrapper for the link:https://github.com/feedhenry/fh-sync[{ProductShortName} datasync server]. The *Datasync Cloud* creates a server side service that allows clients to synchronize offline data to a preferred back-end data store. By default, the Cloud module utilizes a MongoDB database back-end for storing the client data.

For instructions on how to implement the *Datasync Cloud*, see link:{WFM-RC-CoreURL}{WFM-RC-Branch}/cloud/datasync/README.md[README]

To view an example, see the *Datasync Cloud* link:{WFM-RC-CoreUrl}{WFM-RC-Branch}/cloud/datasync/example/index.ts[example].

[id='{context}-datasync-client-module']
== Datasync Client

The *Datasync Client* is based on the link:https://github.com/feedhenry/fh-sync-js[sync.js client]. In order to work, the *Datasync Client* requires the *Datasync Cloud* to be running on an _Express.js_ based web server.
The _Data Synchronization Library_ can be used for offline storage of the client's data.

For instructions on how to implement the *Datasync Client*, see link:{WFM-RC-CoreURL}{WFM-RC-Branch}/client/datasync-client/README.md[README]

To view an example, see the *Datasync Client App* link:{WFM-RC-CoreUrl}{WFM-RC-Branch}/client/datasync-client/example/index.ts[example].
