[id='{context}-pro-running-the-demo-repositories']
= Running the {PROJECT_NAME} Applications on a Local Machine

Get started by running {PROJECT_NAME} applications on your local machine. Follow
these steps and use the _public NPM Registry_ to set up the {PROJECT_NAME}
applications that contain sample Steps, Workflows, and Workorders.

[discrete]
== Prerequisites

The following must be installed on your system:

* Node and npm (tested version: {WFM-RC-NodeVersion})
* git
* MongoDB
* Redis

You must have access to GitHub to install the {PROJECT_NAME} applications.

[id='{context}-published-repositories-cloning-the-git-repositories']
[discrete]
== Cloning the Git Repositories

Clone the Git repositories as follows:
[source,bash]
----
git clone git@github.com:feedhenry-raincatcher/raincatcher-server.git
git clone git@github.com:feedhenry-raincatcher/raincatcher-mobile.git
git clone git@github.com:feedhenry-raincatcher/raincatcher-portal.git
----

The master branch of each Git repository provides the latest version. Previous
versions have the `release-*` tag. For example, run the following command to
checkout version `1.0.0`:

[source,bash]
----
cd raincatcher-server/
git checkout release-1.0.0
----

[id='{context}-published-repositories-installing-repository-dependencies']
[discrete]
== Installing Repository Dependencies

Run the `npm install` command in each repository to download the dependencies.
For example, download dependencies for the Core server as follows:

[source,bash]
----
cd raincatcher-server/
npm install
----

[id='{context}-published-repositories-starting-mongodb-and-redis']
[discrete]
== Starting MongoDB and Redis

Ensure MongoDB and Redis are running on your local machine. For more
information, see:

* MongoDB: https://docs.mongodb.com/manual/tutorial/manage-mongodb-processes/#start-mongod-processes[Start MongoDB Processes]
* Redis: https://redis.io/topics/quickstart#starting-redis[Starting Redis]

[id='{context}-published-repositories-starting-the-core-server']
[discrete]
== Starting the Core Server

Run the `npm run start` command to start the Core server as follows:

[source,bash]
----
cd raincatcher-server/
npm run start
----

NOTE: After you start each {PROJECT_NAME} application, it continues to run in
the terminal. Closing the terminal stops the application. You must start the
Portal and Mobile applications from separate terminals.

[id='{context}-published-repositories-running-the-mobile-and-portal-applications']
[discrete]
== Starting the Portal and Mobile Applications

Start the Portal application first, as follows:

[source,bash]
----
cd raincatcher-portal/
npm run start
----

Next, start the Mobile application as follows:

[source,bash]
----
cd raincatcher-mobile/
npm run start
----

The Portal and Mobile applications automatically open in a browser. If they do
not open automatically, access them at the following URLs:

* Portal application: `http://localhost:9002/?url=http://localhost:8001`
* Mobile application: `http://localhost:9003/?url=http://localhost:8001`

== Credentials for the Portal and Mobile Applications

The Portal and Mobile applications contain sample Steps, Workflows, and
Workorders that you can use to evaluate workforce management processes.

Log in to the Portal and Mobile applications with the following credentials to
access the sample content:

|===
|Application |Username |Password

|Portal
|`max`
|`123`

|Mobile
|`trever`
|`123`
|===

For all available users, see: https://github.com/feedhenry-raincatcher/raincatcher-server/blob/master/src/modules/passport-auth/users.json[users.json]

NOTE: Users are valid for both passport and {Keycloak} auth providers.

As a next step, you can:

* Use the sample Workflows and Workorders. See xref:{context}-pro-using-the-demo-app[Learn to Use Workflows and Workorders].
* Create your own business logic. See xref:building-wfm-process[Building a Workflow].
