[id='{context}-pro-running-the-demo-repositories']
= Running the {PROJECT_NAME} Applications on a Local Machine

Get started by running {PROJECT_NAME} applications on your local machine. Follow
these steps and use the _public NPM Registry_ to set up the {PROJECT_NAME}
applications that contain sample Steps, Workflows, and Workorders.

[discrete]
== Prerequisites

The following must be installed on your system:

* Node and npm (tested version: {WFM-RC-NodeVersion})
* git
* MongoDB
* Redis

You must have access to GitHub to install the {PROJECT_NAME} applications.

[id='{context}-published-repositories-cloning-the-git-repositories']
[discrete]
== Cloning the Git Repositories

The following commands will clone the `master` branch of each repository and they collectively contain the latest tagged release of the {PROJECT_NAME} project.

[source,bash]
----
git clone git@github.com:feedhenry-raincatcher/raincatcher-server.git
git clone git@github.com:feedhenry-raincatcher/raincatcher-mobile.git
git clone git@github.com:feedhenry-raincatcher/raincatcher-portal.git
----

Previous versions are available through branches named with the `release-\{semver\}` convention.
For example, in order to checkout version `0.0.1` of `raincatcher-server`, run the following commands after the cloning:

[source,bash]
----
cd raincatcher-server/
git checkout release-0.0.1
----

[id='{context}-published-repositories-installing-repository-dependencies']
[discrete]
== Installing Repository Dependencies

For each repository previously cloned, run `npm install` so regular NPM dependencies are downloaded.

[id='{context}-published-repositories-starting-mongodb-and-redis']
[discrete]
== Starting MongoDB and Redis

. Start MongoDB. For more information, see link:https://docs.mongodb.com/manual/tutorial/manage-mongodb-processes/#start-mongod-processes[Start MongoDB Processes].

. Start Redis. For more information, see link:https://redis.io/topics/quickstart#starting-redis[Starting Redis].

[id='{context}-published-repositories-starting-the-core-server']
[discrete]
== Starting the Core Server

[source,bash]
----
cd raincatcher-server/
npm run start:ts
----

NOTE: The terminal is out of use while the Core Server is running.

[id='{context}-published-repositories-running-the-mobile-and-portal-applications']
[discrete]
== Running the Mobile and Portal Applications

Open a new terminal and execute the following command in folder `raincatcher-portal/` and also in folder `raincatcher-mobile/`:

[source,bash]
----
npm run start
----

Both the Mobile and Portal Applications open automatically in a browser.

== Credentials for the Portal and Mobile Applications

The Portal and Mobile applications contain sample Steps, Workflows, and
Workorders that you can use to evaluate workforce management processes.

Log in to the Portal and Mobile applications with the following credentials to
access the sample content:

|===
|Application |Username |Password

|Portal
|`max`
|`123`

|Mobile
|`trever`
|`123`
|===

For all available users, see: https://github.com/feedhenry-raincatcher/raincatcher-server/blob/master/src/modules/passport-auth/users.json[users.json]

NOTE: Users are valid for both passport and {Keycloak} auth providers.

As a next step, you can:

* Use the sample Workflows and Workorders. See xref:{context}-pro-using-the-demo-app[Learn to Use Workflows and Workorders].
* Create your own business logic. See xref:building-wfm-process[Building a Workflow].
