[id='{context}-pro-running-the-demo-repositories']
= Running the {PROJECT_NAME} Demonstration Environment

Get started by running a demonstration environment on your local machine. Follow these steps and use the _public NPM Registry_ to set up the {PROJECT_NAME} applications that contain sample Steps, Workflows, and Workorders.

[discrete]
== Requirements

The following must be installed on your system:
* Node and npm (tested version: {WFM-RC-NodeVersion})
* git
* MongoDB (tested version: {WFM-RC-MongoDBVersion})
* Redis (tested version: {WFM-RC-RedisVersion})

You must also have access to:

* `git@github.com:feedhenry-raincatcher/raincatcher-server.git`
* `git@github.com:feedhenry-raincatcher/raincatcher-mobile.git`
* `git@github.com:feedhenry-raincatcher/raincatcher-portal.git`

[discrete]
== Installing and Running the {PROJECT_NAME} Applications

1&#46; Clone the Git repositories.
[source,bash]
----
git clone git@github.com:feedhenry-raincatcher/raincatcher-server.git
git clone git@github.com:feedhenry-raincatcher/raincatcher-mobile.git
git clone git@github.com:feedhenry-raincatcher/raincatcher-portal.git
----

Tip: Cloning the repositories provides the latest version. You can use the `git checkout `release-\{semver\}` command if you want a previous version. For example, `git checkout `release-0.0.1`.

2&#46; Download the NPM dependencies for each Git repostory.
[source,bash]
----
cd /raincatcher-server
npm install
----

3&#46; Ensure MongoDB and Redis are running.

For more information, see:
. MongoDB: https://docs.mongodb.com/manual/tutorial/manage-mongodb-processes/#start-mongod-processes[Start MongoDB Processes]
. Redis: https://redis.io/topics/quickstart#starting-redis[Starting Redis]

4&#46; Start the Core server.
[source,bash]
----
cd raincatcher-server/
npm run start
----

Note: After you start each {PROJECT_NAME} application, it continues to run in the terminal. Closing the terminal stops the application. You must start the Mobile and Portal applications from separate terminals.

5&#46; Start the Mobile application.
[source,bash]
----
cd raincatcher-mobile/
npm run start
----

6&#46; Start the Portal application.
[source,bash]
----
cd raincatcher-portal/
npm run start
----

The Mobile and Portal applications automatically open in a browser.

7&#46; Log in to the Mobile and Portal applications with the following credentials:

|===
|Application |Username |Password

|Mobile
|`trever`
|`123`

|Portal
|`max`
|`123`
|===

For all available users, see: https://github.com/feedhenry-raincatcher/raincatcher-server/blob/master/src/modules/passport-auth/users.json[users.json]

NOTE: Users are valid for both passport and {Keycloak} auth providers.
