[id='{context}-pro-running-the-demo-repositories']
= Running the {PROJECT_NAME} Applications on a Local Machine

Get started by running {PROJECT_NAME} applications on your local machine. Follow
these steps and use the _public NPM Registry_ to set up the {PROJECT_NAME}
applications that contain sample Steps, Workflows, and Workorders.

[discrete]
== Requirements

The following must be installed on your system:

* Node and npm (tested version: {WFM-RC-NodeVersion})
* git
* MongoDB
* Redis

You must have access to GitHub to install the {PROJECT_NAME} applications.

[id='{context}-published-repositories-cloning-the-git-repositories']
[discrete]
== Clone the Git Repositories

Clone the Git repositories as follows:
[source,bash]
----
git clone git@github.com:feedhenry-raincatcher/raincatcher-server.git
git clone git@github.com:feedhenry-raincatcher/raincatcher-mobile.git
git clone git@github.com:feedhenry-raincatcher/raincatcher-portal.git
----

The master branch of each Git repository provides the latest version. Previous
versions have the `release-*` tag. For example, run the following command to
checkout version `1.0.0`:

[source,bash]
----
cd raincatcher-server/
git checkout release-1.0.0
----

[id='{context}-published-repositories-installing-repository-dependencies']
[discrete]
== Install the Dependencies for Each Repository

Run the `npm install` command in each repository to download the dependencies.
For example, download dependencies for the Core server as follows:
[source,bash]
----
cd raincatcher-server/
npm install
----

[id='{context}-published-repositories-starting-mongodb-and-redis']
[discrete]
== Start MongoDB and Redis

Ensure MongoDB and Redis are running on your local machine. For more
information, see:

* MongoDB: https://docs.mongodb.com/manual/tutorial/manage-mongodb-processes/#start-mongod-processes[Start MongoDB Processes]
* Redis: https://redis.io/topics/quickstart#starting-redis[Starting Redis]

[id='{context}-published-repositories-starting-the-core-server']
[discrete]
== Start the Core Server

Run the `npm run start` command to start the Core server as follows:
[source,bash]
----
cd raincatcher-server/
npm run start
----

NOTE: After you start each {PROJECT_NAME} application, it continues to run in the terminal. Closing the terminal stops the application. You must start the Mobile and Portal applications from separate terminals.

[id='{context}-published-repositories-running-the-mobile-and-portal-applications']
[discrete]
== Start the Portal and Mobile Applications

1&#46; Start the Portal application as follows:
[source,bash]
----
cd raincatcher-portal/
npm run start
----

2&#46; Start the Mobile application as follows:
[source,bash]
----
cd raincatcher-mobile/
npm run start
----

The Portal and Mobile applications automatically open in a browser at the
following URLs:

* Portal application: `http://localhost:8001/cookie-login`
* Mobile application: `http://localhost:9002/?url=http://localhost:8001#!/workorders/list`

== Credentials for the Portal and Mobile Applications

You can log in to the Portal and Mobile applications with the following
credentials:

|===
|Application |Username |Password

|Mobile
|`trever`
|`123`

|Portal
|`max`
|`123`
|===

For all available users, see: https://github.com/feedhenry-raincatcher/raincatcher-server/blob/master/src/modules/passport-auth/users.json[users.json]

NOTE: Users are valid for both passport and {Keycloak} auth providers.
