[id='{context}-ref-keycloak-securitystrategy']
= Defining the Security Strategy for {PROJECT_NAME} {Keycloak}

[id='{context}-understanding-keycloak-terminologies']
[discrete]
== Understanding {Keycloak} Terminologies
There are some key concepts and terminologies to be aware of before using {Keycloak}. For more
information on these key concepts and terminologies, refer to the {Keycloak} Core Concepts documentation.

[id='{context}-understanding-keycloak-client-adapters']
[discrete]
== Understanding {Keycloak} Client Adapters
{PROJECT_NAME} uses the Node.js Client Adapter for the {PROJECT_NAME} server and the Javascript Client Adapter for the {PROJECT_NAME} mobile and portal.

For more information on the Node.js Client Adapter, see the link:https://github.com/keycloak/keycloak-nodejs-connect/blob/master/README.md[{Keycloak} Node.js Adapter]
For more information on the Javascript Client Adapter, see the link:https://github.com/keycloak/keycloak-js-bower/blob/master/README.md[Javascript Adapter] documentation.

[id='{context}-understanding-keycloak-session-management']
[discrete]
== Understanding {Keycloak} Session Management
The _express-session_ module provides session management functionality and
the management of sessions is performed on the {Keycloak} server
For more information on _express-session_, see link:https://github.com/expressjs/session[express-session].

[id='{context}-defining-keycloak-access-control']
[discrete]
== Defining {Keycloak} Access Control
{Keycloak} provides role-based access control and is configured on the {Keycloak} server.

See the xref:{context}-protect-express-routes[Protect Express Routes] section on how routes are protected in the application.
For more information on protecting express routes, see the {Keycloak} link:https://github.com/keycloak/keycloak-nodejs-connect/blob/master/README.md[Node.js Adapter].

[id='{context}-defining-keycloak-password-storage']
[discrete]
== Defining {Keycloak} Password Storage
{Keycloak} uses the link:https://en.wikipedia.org/wiki/PBKDF2[PBKDF2 algorithm] for password hashing by default.
{Keycloak} also provides enforced password policies from the server.

For more information on server administration topics, see link:https://github.com/keycloak/keycloak/blob/master/README.md[{Keycloak} documentation] on identity-broker and user federation.

[id='{context}-keycloak-authentication']
[discrete]
== {Keycloak} Authentication
{Keycloak} has a wide variety of authentication mechanisms available. For more information, refer to the {Keycloak} Authentication Documentation.

[id='{context}-keycloak-authorization']
[discrete]
== {Keycloak} Authorization
Authorization is fully documented in the {Keycloak} Authorization Documentation.
